"""Model Selector — resolves 'model: auto' requests for the Forecast API.

This is the bridge between model_comparison.py's output (model_selection.json)
and the FastAPI forecast endpoint / Forecast Agent. It deliberately knows
NOTHING about how forecasts are actually generated — it only answers one
question: "given a category and a requested model (possibly 'auto'), which
concrete model should be invoked?"

Usage in your FastAPI endpoint:

    from forecasting.model_selector import ModelSelector

    selector = ModelSelector()  # loaded once at app startup

    @app.post("/forecast")
    def forecast(req: ForecastRequest):
        resolved = selector.resolve(req.category, req.model)
        # resolved.model            -> "gbm" | "lstm" | "baseline"
        # resolved.confidence       -> "high" | "low"
        # resolved.reason           -> human-readable string for the response/UI
        # resolved.was_auto_resolved -> True if caller passed "auto"
        ...
        return {
            "category": req.category,
            "model_used": resolved.model,
            "confidence": resolved.confidence,
            "selection_reason": resolved.reason,
            "forecast": [...],
        }

Reload behavior: model_selection.json is re-generated by model_comparison.py
each time the pipeline reruns. ModelSelector caches it in memory; call
selector.reload() (or just re-instantiate) after a pipeline rerun, or pass
auto_reload=True to re-stat the file on every resolve() call (cheap: just an
mtime check, not a full re-parse, unless the file actually changed).
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from dataclasses import dataclass
from typing import Optional

log = logging.getLogger("model_selector")

DEFAULT_SELECTION_PATH = Path(__file__).parent.parent / "data" / "processed" / "model_selection.json"

VALID_MODELS = {"baseline", "lstm", "gbm"}


class ModelSelectionUnavailable(RuntimeError):
    """Raised when model_selection.json is missing or unreadable and no
    safe fallback can be determined. The API layer should catch this and
    return a 503 — silently guessing a model to serve is worse than a
    clear error, especially before the pipeline has ever been run."""


@dataclass
class ResolvedModel:
    model: str                      # "gbm" | "lstm" | "baseline"
    confidence: str                 # "high" | "low" | "unknown"
    reason: str
    requested: str                  # what the caller originally asked for
    was_auto_resolved: bool
    category: str
    category_known: bool            # False if this category wasn't in model_selection.json


class ModelSelector:
    def __init__(self, selection_path: Optional[Path] = None, auto_reload: bool = True):
        self.selection_path = Path(selection_path) if selection_path else DEFAULT_SELECTION_PATH
        self.auto_reload = auto_reload
        self._mtime: Optional[float] = None
        self._data: Optional[dict] = None
        self._load()

    # ── internal ──────────────────────────────────────────────────────

    def _load(self) -> None:
        if not self.selection_path.exists():
            raise ModelSelectionUnavailable(
                f"{self.selection_path} not found. Run model_comparison.py first "
                f"to generate it before serving forecasts."
            )
        with open(self.selection_path) as f:
            data = json.load(f)

        required_top = {"global_default_model", "per_category"}
        missing = required_top - set(data.keys())
        if missing:
            raise ModelSelectionUnavailable(
                f"{self.selection_path} is missing required key(s) {sorted(missing)}. "
                f"It may have been written by an incompatible version of model_comparison.py."
            )
        if data["global_default_model"] not in VALID_MODELS:
            raise ModelSelectionUnavailable(
                f"global_default_model='{data['global_default_model']}' is not one of {VALID_MODELS}."
            )

        self._data = data
        self._mtime = self.selection_path.stat().st_mtime
        log.info(f"  Loaded model selection: global_default={data['global_default_model']}, "
                 f"{len(data['per_category'])} categories")

    def _maybe_reload(self) -> None:
        if not self.auto_reload:
            return
        try:
            current_mtime = self.selection_path.stat().st_mtime
        except FileNotFoundError:
            return  # keep serving the last good copy rather than crashing live traffic
        if current_mtime != self._mtime:
            log.info("  model_selection.json changed on disk — reloading")
            try:
                self._load()
            except ModelSelectionUnavailable as e:
                log.error(f"  Reload failed, continuing with stale data: {e}")

    def reload(self) -> None:
        self._load()

    # ── public API ───────────────────────────────────────────────────

    def resolve(self, category: str, requested_model: str = "auto") -> ResolvedModel:
        """Resolves a (category, requested_model) pair to a concrete model.

        requested_model:
            "auto"               -> use the per-category selection, falling
                                     back to the global default if the
                                     category is unknown.
            "baseline"/"lstm"/"gbm" -> honored as an explicit override,
                                     passed straight through (validated).
        """
        self._maybe_reload()
        assert self._data is not None

        requested_model = (requested_model or "auto").strip().lower()

        if requested_model != "auto":
            if requested_model not in VALID_MODELS:
                raise ValueError(
                    f"Unknown model '{requested_model}'. Must be 'auto' or one of {sorted(VALID_MODELS)}."
                )
            return ResolvedModel(
                model=requested_model,
                confidence="unknown",
                reason=f"Explicitly requested by caller (override of auto-selection).",
                requested=requested_model,
                was_auto_resolved=False,
                category=category,
                category_known=category in self._data["per_category"],
            )

        cat_info = self._data["per_category"].get(category)
        if cat_info is None:
            return ResolvedModel(
                model=self._data["global_default_model"],
                confidence="low",
                reason=(f"Category '{category}' has no entry in model_selection.json "
                        f"(new/unseen category) — using the global default model "
                        f"('{self._data['global_default_model']}')."),
                requested="auto",
                was_auto_resolved=True,
                category=category,
                category_known=False,
            )

        return ResolvedModel(
            model=cat_info["selected_model"],
            confidence=cat_info.get("confidence", "unknown"),
            reason=cat_info.get("reason", ""),
            requested="auto",
            was_auto_resolved=True,
            category=category,
            category_known=True,
        )

    def known_categories(self) -> list[str]:
        self._maybe_reload()
        return sorted(self._data["per_category"].keys()) if self._data else []

    def global_default(self) -> str:
        self._maybe_reload()
        return self._data["global_default_model"] if self._data else "baseline"


# ── quick manual check ──────────────────────────────────────────────────
if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    selector = ModelSelector()
    print(f"Global default: {selector.global_default()}")
    print(f"Known categories: {selector.known_categories()}")
    for cat in selector.known_categories():
        r = selector.resolve(cat, "auto")
        print(f"  {cat:25s} -> {r.model:10s} ({r.confidence})")
    # Unseen category should gracefully fall back
    r = selector.resolve("some_brand_new_category", "auto")
    print(f"\nUnseen category fallback -> {r.model} ({r.reason})")
    # Explicit override should pass through
    r = selector.resolve("telephony", "baseline")
    print(f"Explicit override -> {r.model} ({r.reason})")
